/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as QuizQuizIdPublicRouteImport } from './routes/quiz/$quizId/public'
import { Route as DashboardQuizNewRouteImport } from './routes/dashboard/quiz/new'
import { Route as DashboardQuizQuizIdRouteImport } from './routes/dashboard/quiz/$quizId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizQuizIdPublicRoute = QuizQuizIdPublicRouteImport.update({
  id: '/quiz/$quizId/public',
  path: '/quiz/$quizId/public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardQuizNewRoute = DashboardQuizNewRouteImport.update({
  id: '/quiz/new',
  path: '/quiz/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardQuizQuizIdRoute = DashboardQuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/new': typeof DashboardQuizNewRoute
  '/quiz/$quizId/public': typeof QuizQuizIdPublicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/new': typeof DashboardQuizNewRoute
  '/quiz/$quizId/public': typeof QuizQuizIdPublicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/quiz/$quizId': typeof DashboardQuizQuizIdRoute
  '/dashboard/quiz/new': typeof DashboardQuizNewRoute
  '/quiz/$quizId/public': typeof QuizQuizIdPublicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/new'
    | '/quiz/$quizId/public'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/new'
    | '/quiz/$quizId/public'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/signin'
    | '/auth/signup'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/quiz/$quizId'
    | '/dashboard/quiz/new'
    | '/quiz/$quizId/public'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  QuizQuizIdPublicRoute: typeof QuizQuizIdPublicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$quizId/public': {
      id: '/quiz/$quizId/public'
      path: '/quiz/$quizId/public'
      fullPath: '/quiz/$quizId/public'
      preLoaderRoute: typeof QuizQuizIdPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/quiz/new': {
      id: '/dashboard/quiz/new'
      path: '/quiz/new'
      fullPath: '/dashboard/quiz/new'
      preLoaderRoute: typeof DashboardQuizNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/quiz/$quizId': {
      id: '/dashboard/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/dashboard/quiz/$quizId'
      preLoaderRoute: typeof DashboardQuizQuizIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardQuizQuizIdRoute: typeof DashboardQuizQuizIdRoute
  DashboardQuizNewRoute: typeof DashboardQuizNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardQuizQuizIdRoute: DashboardQuizQuizIdRoute,
  DashboardQuizNewRoute: DashboardQuizNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  QuizQuizIdPublicRoute: QuizQuizIdPublicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
