/**
 * Quiz Status Enum
 *
 * Defines the generation status of a quiz:
 * - GENERATING: Quiz is being generated by the AI workflow
 * - READY: Quiz generation completed successfully
 * - FAILED: Quiz generation failed after all retry attempts
 */
export enum QuizStatus {
  GENERATING = "generating",
  READY = "ready",
  FAILED = "failed",
}

/**
 * Type guard to check if a value is a valid QuizStatus
 */
export function isQuizStatus(value: unknown): value is QuizStatus {
  return (
    typeof value === "string" &&
    Object.values(QuizStatus).includes(value as QuizStatus)
  );
}

/**
 * Get display name for a QuizStatus value
 */
export function getQuizStatusDisplayName(status: QuizStatus): string {
  const displayNames: Record<QuizStatus, string> = {
    [QuizStatus.GENERATING]: "Generating",
    [QuizStatus.READY]: "Ready",
    [QuizStatus.FAILED]: "Failed",
  };
  return displayNames[status];
}

/**
 * Get description for a QuizStatus value
 */
export function getQuizStatusDescription(status: QuizStatus): string {
  const descriptions: Record<QuizStatus, string> = {
    [QuizStatus.GENERATING]: "Quiz is being generated by AI",
    [QuizStatus.READY]: "Quiz is ready to be taken",
    [QuizStatus.FAILED]: "Quiz generation failed",
  };
  return descriptions[status];
}
