// Application Layer - Application Business Rules
// This layer contains use-case specific business logic and orchestrates data flow.

// Ports (Interfaces)
export type {
  // Repository Interfaces
  IQuizRepository,
  IQuestionRepository,
  IAttemptRepository,
  ISourceMaterialRepository,
  PaginationParams,
  PaginatedResult,
  // Service Interfaces
  IAIQuizGenerator,
  GenerateQuizParams,
  StreamGenerateQuizParams,
  StreamingProgressCallback,
  GeneratedQuestionData,
  FileMetadata,
  IFileStorageService,
  IS3StorageService,
  FileUploadRequest,
  PresignedUploadUrl,
  ICacheService,
  IIdGenerator,
  IQuizGenerationEventPublisher,
  IQuizGenerationEventSubscriber,
  // Generic Pub/Sub Interfaces
  IEventPublisher,
  IEventSubscriber,
  IPubSub,
  EventHandler,
  Unsubscribe,
  ChannelEvent,
} from "./ports";

// DTOs
export {
  // Quiz DTOs
  createQuizInputSchema,
  quizResponseSchema,
  quizDistributionSchema,
  visibilitySchema,
  updateQuizVisibilitySchema,
  toQuizResponseDTO,
  type CreateQuizInput,
  type QuizResponseDTO,
  // Question DTOs
  questionOptionSchema,
  questionResponseSchema,
  toQuestionResponseDTO,
  type QuestionResponseDTO,
  // Pagination DTOs
  paginationInputSchema,
  createPaginatedResponseSchema,
  type PaginationInput,
  type PaginatedResponseDTO,
  // Attempt DTOs
  attemptStatusSchema,
  startAttemptInputSchema,
  submitAttemptInputSchema,
  attemptResponseSchema,
  getUserAttemptsInputSchema,
  getAttemptBySlugInputSchema,
  toAttemptResponseDTO,
  createAttemptSummary,
  type StartAttemptInput,
  type SubmitAttemptInput,
  type AttemptResponseDTO,
  type GetUserAttemptsInput,
  type GetAttemptBySlugInput,
  type AttemptSummaryDTO,
} from "./dtos";

// Use Cases (via feature modules)
export {
  CreateQuizUseCase,
  type CreateQuizUseCaseInput,
  type CreateQuizUseCaseDeps,
  GetUserQuizzesUseCase,
  type GetUserQuizzesInput,
  type GetUserQuizzesUseCaseDeps,
  GetQuizByIdUseCase,
  type GetQuizByIdInput,
  type GetQuizByIdOutput,
  type GetQuizByIdUseCaseDeps,
  ShareQuizUseCase,
  type ShareQuizInput,
  type ShareQuizOutput,
  type ShareQuizUseCaseDeps,
  DeleteQuizUseCase,
  type DeleteQuizInput,
  type DeleteQuizUseCaseDeps,
  UpdateQuizVisibilityUseCase,
  type UpdateQuizVisibilityInput,
  type UpdateQuizVisibilityOutput,
  type UpdateQuizVisibilityUseCaseDeps,
  StartAttemptUseCase,
  ForceStartAttemptUseCase,
  type StartAttemptInput as StartAttemptUseCaseInput,
  type StartAttemptOutput,
  type StartAttemptUseCaseDeps,
  type ForceStartAttemptInput,
  SubmitAttemptUseCase,
  type SubmitAttemptOutput,
  type SubmitAttemptUseCaseDeps,
  GetUserAttemptsUseCase,
  type GetUserAttemptsInput as GetUserAttemptsUseCaseInput,
  type GetUserAttemptsOutput,
  type GetUserAttemptsUseCaseDeps,
  GetAttemptDetailUseCase,
  type GetAttemptDetailInput,
  type GetAttemptDetailOutput,
  type GetAttemptDetailUseCaseDeps,
  AutosaveAnswerUseCase,
  type AutosaveAnswerInput,
  type AutosaveAnswerOutput,
  type AutosaveAnswerUseCaseDeps,
  ResetAttemptUseCase,
  type ResetAttemptInput,
  type ResetAttemptOutput,
  type ResetAttemptUseCaseDeps,
  GetUserAttemptHistoryUseCase,
  type GetUserAttemptHistoryInput,
  type GetUserAttemptHistoryOutput,
  type AttemptHistoryItemDTO,
  type GetUserAttemptHistoryUseCaseDeps,
  GetPresignedUploadUrlsUseCase,
  getPresignedUploadUrlsInputSchema,
  type GetPresignedUploadUrlsInput,
  type GetPresignedUploadUrlsOutput,
  type GetPresignedUploadUrlsUseCaseDeps,
  // Policy (generation logic moved to Upstash Workflow)
  QuizGenerationPolicy,
  type ModelFallbackResult,
} from "./use-cases";

// Errors
export {
  ApplicationError,
  NotFoundError,
  UnauthorizedError,
  ForbiddenError,
  ValidationError,
  QuotaExceededError,
  ExternalServiceError,
} from "./errors";

// Types
export {
  AIModel,
  isAIModel,
  getAIModelDisplayName,
  DEFAULT_AI_MODEL,
} from "./types";
